work on proprety Api
Muhindo-Galien/HauZy pull request #9
Opened 2021-07-13 18:33 UTC by Muhindo-Galien

closes #ISSUE-NO

work on the property's API
## Tasks

- [ # ] User can post a property
- [#  ] user can update aproperty
- [ # ] user can delete aproperty
- [#  ] user can get a signle propery by property_id
- [#  ] user can get properties

2021-07-13 18:39 UTC, Muhindo-Galien commented
LGTM

2021-07-13 18:40 UTC, Muhindo-Galien commented
LGTM

2021-07-13 18:41 UTC, Muhindo-Galien commented
LGTM

2021-07-14 08:46 UTC, desirekaleba requested changes
Check all my comments and update the code accordingly. Once you finish, push your updates and rerequest the reviewer again.

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +exports.propertyCreate = async(req,res) => {
Use `createProperty` as the function name.

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +  const nweProperty = new Property({
`newProperty` not `nweProperty`

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +  console.log(req.user)
No `console.log`

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +exports.propertyUpdate = async(req, res) => {
Use `updateProperty` as the function name.

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +exports.propertyDelete = async(req, res) => {
This too should be `deleteProperty`

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +exports.propertyGetAll = async(req, res) => {
`getAllPropertiesByType` as function name.

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +exports.propertyGetOne = async(req, res) => {
`getPropertyById` as function name.

2021-07-14 08:46 UTC, desirekaleba commented on controllers/properties.js
> +// }
Removed unused code. And add logic for getting all properties without any filter. use `getAllProperties` as the function name.

2021-07-14 08:46 UTC, desirekaleba commented on middlewares/authToken.js
> +exports.authToken = (req, res, next) => {
Use `isAuthenticated` as your middleware name.

2021-07-14 08:46 UTC, desirekaleba commented on middlewares/authToken.js
> +  jwt.verify(token, process.env.JWT_SECRET_KEY, (err,user) => {
Use the token until file to verify your token. Precisely the `compare` method.

2021-07-14 08:46 UTC, desirekaleba commented on middlewares/authToken.js
> +  jwt.verify(token, process.env.JWT_SECRET_KEY, (err,user) => {
update it to bind the user to your request.

2021-07-14 08:46 UTC, desirekaleba commented on models/Property.js
> +  price : String,
price should be a floating number.

2021-07-14 08:46 UTC, desirekaleba commented on routes/property.js
> +const { propertyCreate,propertyUpdate,propertyGetOne,propertyGetAll, propertyDelete } = require('../controllers/properties');
Update these accordingly.

2021-07-14 08:46 UTC, desirekaleba commented on routes/property.js
> +router.route('/').get(propertyGetAll);
This is getting by type. create `getAllProperties` and use it here.

2021-07-14 08:46 UTC, desirekaleba commented on routes/property.js
> +router.route('/').get(propertyGetAll);
You should add filtering by type too.

2021-07-14 08:46 UTC, desirekaleba commented on server.js
> +
Remove this blank space.

2021-07-17 07:52 UTC, desirekaleba approved these changes
I'll merge but still need some changes. I'll discuss with you those changes as the project grows

2021-07-17 07:52 UTC, desirekaleba commented on routes/flag.js
> +router.route('/flag/:propertyId').delete(isAuthenticated,deleteFlag);
:flagId

2021-07-17 07:52 UTC, merged